export const projections = [
    {
        id: 0,
        shader: 'plate-carree',
        name: 'Plate Carr\u00e9e (Equirectangular)',
        emoji: '\ud83d\uddfa\ufe0f',
        properties: ['Equidistant'],
        creators: ['Marinus of Tyre'],
        originated: '~100 AD',
        summary: 'One of the oldest and simplest map projections. It maps meridians to evenly spaced vertical lines and parallels to evenly spaced horizontal lines. While it distorts shapes and areas significantly away from the standard parallels, its simplicity makes it the most common format for storing raster geographic data.',
        resources: [
            { title: 'Wikipedia: Equirectangular Projection', url: 'https://en.wikipedia.org/wiki/Equirectangular_projection' },
            { title: 'Map Projections: A Working Manual (USGS)', url: 'https://pubs.usgs.gov/pp/1395/report.pdf' },
        ],
    },
    {
        id: 1,
        shader: 'mercator',
        name: 'Mercator',
        emoji: '\ud83e\udded',
        properties: ['Conformal'],
        creators: ['Gerardus Mercator'],
        originated: '1569',
        summary: 'A cylindrical projection designed for nautical navigation that preserves local angles and shapes (conformality). Any straight line on the map is a line of constant bearing (rhumb line), making it invaluable for marine charts. Its extreme area distortion near the poles has made it controversial for world maps, but it remains the basis for most web mapping tiles.',
        resources: [
            { title: 'Wikipedia: Mercator Projection', url: 'https://en.wikipedia.org/wiki/Mercator_projection' },
            { title: 'The True Size Of...', url: 'https://www.thetruesize.com/' },
            { title: 'Why Are We Still Using Mercator?', url: 'https://geoawesomeness.com/why-are-we-still-using-mercator/' },
        ],
    },
    {
        id: 2,
        shader: 'orthographic',
        name: 'Orthographic',
        emoji: '\ud83c\udf0d',
        properties: ['Azimuthal'],
        creators: ['Ancient Greek astronomers'],
        originated: '~200 BC',
        summary: 'Depicts a hemisphere of the globe as it would appear from infinite distance, resembling a photograph of the Earth from space. It provides a natural and intuitive perspective view, but only one hemisphere is visible at a time and distortion increases rapidly toward the edges.',
        resources: [
            { title: 'Wikipedia: Orthographic Map Projection', url: 'https://en.wikipedia.org/wiki/Orthographic_map_projection' },
            { title: 'Wolfram MathWorld: Orthographic Projection', url: 'https://mathworld.wolfram.com/OrthographicProjection.html' },
        ],
    },
    {
        id: 3,
        shader: 'vertical-perspective',
        name: 'Vertical Perspective',
        emoji: '\ud83d\udef0\ufe0f',
        properties: ['Azimuthal'],
        creators: ['Ancient Greek astronomers'],
        originated: '~150 BC',
        summary: 'A generalization of the orthographic projection that simulates the view from a finite altitude above the Earth. Often called the "near-side perspective" projection, it produces views similar to satellite or aerial photography. Used extensively by NASA and in television graphics to show realistic views of Earth.',
        resources: [
            { title: 'Wikipedia: General Perspective Projection', url: 'https://en.wikipedia.org/wiki/General_Perspective_projection' },
            { title: 'NASA Visible Earth', url: 'https://visibleearth.nasa.gov/' },
        ],
    },
    {
        id: 4,
        shader: 'azimuthal-equidistant',
        name: 'Azimuthal Equidistant',
        emoji: '\ud83d\udce1',
        properties: ['Azimuthal', 'Equidistant'],
        creators: ['Guillaume Postel'],
        originated: '1581',
        summary: 'Preserves both distance and direction from the center point to every other point on the map. This makes it ideal for showing airline routes, radio transmission ranges, and seismic distances. The emblem of the United Nations features an azimuthal equidistant projection centered on the North Pole.',
        resources: [
            { title: 'Wikipedia: Azimuthal Equidistant Projection', url: 'https://en.wikipedia.org/wiki/Azimuthal_equidistant_projection' },
            { title: 'UN Emblem and Flag', url: 'https://www.un.org/en/about-us/un-emblem-and-flag' },
        ],
    },
    {
        id: 5,
        shader: 'stereographic',
        name: 'Stereographic',
        emoji: '\u2b55',
        properties: ['Conformal', 'Azimuthal'],
        creators: ['Hipparchus'],
        originated: '~150 BC',
        summary: 'Projects the sphere from a point on the surface to a tangent plane at the antipodal point. It is the only map projection that is both conformal and azimuthal, making it essential for polar maps, crystallography, and complex analysis. The Universal Polar Stereographic (UPS) system uses it for mapping high-latitude regions.',
        resources: [
            { title: 'Wikipedia: Stereographic Map Projection', url: 'https://en.wikipedia.org/wiki/Stereographic_map_projection' },
            { title: 'Wolfram MathWorld: Stereographic Projection', url: 'https://mathworld.wolfram.com/StereographicProjection.html' },
        ],
    },
    {
        id: 6,
        shader: 'sinusoidal',
        name: 'Sinusoidal',
        emoji: '\u3030\ufe0f',
        properties: ['Equal-Area'],
        creators: ['Jean Cossin', 'Nicolas Sanson'],
        originated: '1570',
        summary: 'A pseudocylindrical equal-area projection where the parallels are equally spaced horizontal lines and the meridians are sinusoidal curves. It accurately represents area at the cost of shape distortion, especially near the map edges, and is widely used in global climate and vegetation datasets where preserving area is essential.',
        resources: [
            { title: 'Wikipedia: Sinusoidal Projection', url: 'https://en.wikipedia.org/wiki/Sinusoidal_projection' },
            { title: 'NASA MODIS Sinusoidal Grid', url: 'https://modis-land.gsfc.nasa.gov/MODLAND_grid.html' },
        ],
    },
    {
        id: 7,
        shader: 'lambert-azimuthal',
        name: 'Lambert Azimuthal Equal-Area',
        emoji: '\ud83c\udfaf',
        properties: ['Equal-Area', 'Azimuthal'],
        creators: ['Johann Heinrich Lambert'],
        originated: '1772',
        summary: 'Preserves area while also being azimuthal, meaning directions from the center are correct. It is widely used for continental and hemispheric maps where accurate area representation is important. The European Environment Agency and many national atlases use it as their standard projection.',
        resources: [
            { title: 'Wikipedia: Lambert Azimuthal Equal-Area Projection', url: 'https://en.wikipedia.org/wiki/Lambert_azimuthal_equal-area_projection' },
            { title: 'EPSG:3035 - ETRS89 / LAEA Europe', url: 'https://epsg.io/3035' },
        ],
    },
    {
        id: 8,
        shader: 'gnomonic',
        name: 'Gnomonic',
        emoji: '\ud83d\udcd0',
        properties: ['Azimuthal', 'Gnomonic'],
        creators: ['Thales of Miletus'],
        originated: '~580 BC',
        summary: 'The oldest known map projection. It projects from the center of the Earth, causing all great circles to appear as straight lines. This unique property makes it indispensable for planning the shortest routes in aviation and maritime navigation, though it can only show less than a hemisphere and distortion grows extreme near the edges.',
        resources: [
            { title: 'Wikipedia: Gnomonic Projection', url: 'https://en.wikipedia.org/wiki/Gnomonic_projection' },
            { title: 'Great Circle Mapper', url: 'https://www.greatcirclemapper.net/' },
        ],
    },
    {
        id: 9,
        shader: 'mollweide',
        name: 'Mollweide',
        emoji: '\ud83e\udd5a',
        properties: ['Equal-Area'],
        creators: ['Karl Mollweide'],
        originated: '1805',
        summary: 'A pseudocylindrical equal-area projection that maps the entire globe into an ellipse. It balances shape and area distortion more evenly than the sinusoidal projection, making it a popular choice for world maps showing distributions of phenomena like population, climate, or ocean currents.',
        resources: [
            { title: 'Wikipedia: Mollweide Projection', url: 'https://en.wikipedia.org/wiki/Mollweide_projection' },
            { title: 'Wolfram MathWorld: Mollweide Projection', url: 'https://mathworld.wolfram.com/MollweideProjection.html' },
        ],
    },
];
